
const challenges=[
{type:'coding',label:'Coding',title:'Python Output',question:'What does this code print?',code:'numbers = [2, 4, 6]\nprint(sum(numbers) / len(numbers))',answer:'It prints 4.0 because the average of 2, 4, and 6 is 4.'},
{type:'coding',label:'Coding',title:'Debug Thinking',question:'A robot should move 5 steps, but it moves forever. What concept should students check first?',code:'while moving:\n    robot.forward()',answer:'They should check the loop condition. The loop may never become false.'},
{type:'math',label:'Math',title:'SAT-Style Linear Equation',question:'If 3x + 7 = 22, what is x?',code:'',answer:'x = 5 because 22 - 7 = 15 and 15 divided by 3 is 5.'},
{type:'math',label:'Math',title:'Probability',question:'A bag has 3 red blocks and 2 blue blocks. What is the probability of picking a blue block?',code:'',answer:'2/5 or 40%, because there are 2 blue blocks out of 5 total blocks.'},
{type:'ai',label:'AI',title:'Classification',question:'A model predicts whether an email is spam or not spam. What type of machine learning task is this?',code:'',answer:'Classification, because the model chooses between categories.'},
{type:'ai',label:'AI',title:'Bias Question',question:'Why should students ask where an AI training dataset came from?',code:'',answer:'Because the source of the data can affect fairness, accuracy, and bias.'},
{type:'beyond-ai',label:'Beyond AI',title:'Human Judgment',question:'If AI gives an answer that sounds confident, what should a student still do?',code:'',answer:'Check the reasoning, verify the source, compare evidence, and decide whether the answer makes sense.'},
{type:'beyond-ai',label:'Beyond AI',title:'Systems Thinking',question:'Why is launching a STEM program more than choosing tools?',code:'',answer:'Because strong programs need goals, curriculum, trained instructors, student support, assessment, communication, and outcomes.'}
];
const grid=document.getElementById('challengeGrid'),filters=document.querySelectorAll('[data-filter]');
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function render(filter='all'){if(!grid)return;const list=filter==='all'?challenges:challenges.filter(c=>c.type===filter);grid.innerHTML=list.map(c=>`<article class="challenge-card"><span class="tag">${c.label}</span><h3>${esc(c.title)}</h3><p>${esc(c.question)}</p>${c.code?`<pre><code>${esc(c.code)}</code></pre>`:''}<button class="btn secondary reveal-answer" type="button">Reveal Answer</button><p class="challenge-answer">${esc(c.answer)}</p></article>`).join('');document.querySelectorAll('.reveal-answer').forEach(btn=>btn.addEventListener('click',()=>{const ans=btn.nextElementSibling;ans.classList.toggle('open');btn.textContent=ans.classList.contains('open')?'Hide Answer':'Reveal Answer'}))}
filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter)}));render();
const quiz=document.getElementById('quiz'),result=document.getElementById('quizResult');
if(quiz){quiz.querySelectorAll('button[data-correct]').forEach(btn=>btn.addEventListener('click',()=>{quiz.querySelectorAll('button[data-correct]').forEach(b=>b.classList.remove('correct','wrong'));const ok=btn.dataset.correct==='true';btn.classList.add(ok?'correct':'wrong');result.textContent=ok?'Correct. Tools come after goals, not before. Planning has entered the chat.':'Not quite. Define goals, age group, budget, timeline, and outcomes first.'}))}
